Dev-Prison/Effective-Java

app/src/main/java/com/programmers/java/chapt3/item13/Main.java
app/src/main/java/com/programmers/java/chapt3/item13/README.md
app/src/main/java/com/programmers/java/chapt3/item13/Stack.java
app/src/test/java/com/programmers/java/chapt3/item13/StackTest.java

feat: item13 

---

app/src/main/java/com/programmers/java/JVM/김병연/README.md
app/src/main/java/com/programmers/java/JVM/김병연/Test.java

- 1부
- 전반적인 자바의 메모리 할당 및 실행 과정
- 각 메모리 영역 역할
- 2부
- call by value 메모리 할당 과정 설명
- [[[Java] Java는 Call by reference가 없다](https://deveric.tistory.com/92)](https://deveric.tistory.com/92)
- os와 상호작용 과정
- 3부
- 클래스로더
- 동작원리
- 구성요소

feat : JVM 톺아보기_엘리자베스

---

app/src/main/java/com/programmers/java/JVM/김병연/README.md

- GC 가 무엇인지
- GC가 왜 있어야 하는지
- GC 종류 및 설명
- GC의 장점 및 단점
- GC의 메모리 수거 방법

feat : GC 톺아보기

---

app/src/main/java/com/programmers/java/chapt4/item23/README.md

item23 태그 달린 클래스보다는 클래스 계층 구조를 활용하라

---

app/src/main/java/com/programmers/java/chapt6/item34.md

[노션 바로가기](https://cat-tungsten-c56.notion.site/DAY11-int-0e2e8c277d2648f59fcf624fc2234588)

Item34 - int 상수 대신 열거 타입을 사용하라

---

app/src/main/java/com/programmers/java/chapt6/item37/Phase.java
app/src/main/java/com/programmers/java/chapt6/item37/Plant.java
app/src/main/java/com/programmers/java/chapt6/item37/PlantManager.java
app/src/main/java/com/programmers/java/chapt6/item37/item37_EnumMap을_사용하라.md

* Item37 ordinal 인덱싱 대신 EnumMap을 사용하라 챕터 정리하였습니다 :) 
[노션링크](https://morning-paprika-8fa.notion.site/Item37-EnumMap-54f6685b29d24a5bba0d749770bb2aa2)

 Item37 -  ordinal 인덱싱 대신 EnumMap을 사용하라

---

app/src/main/java/com/programmers/java/chapt6/item36/Item36_비트_필드_대신_EnumSet을_사용하라.md

[[이펙티브자바] item36. 비트 필드 대신 EnumSet을 사용하라.](https://velog.io/@yhlee9753/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C%EC%9E%90%EB%B0%94-item36.-%EB%B9%84%ED%8A%B8-%ED%95%84%EB%93%9C-%EB%8C%80%EC%8B%A0-EnumSet%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%98%EB%9D%BC)

Item36 - 비트 필드 대신 EnumSet을 사용하라

---

app/src/main/java/com/programmers/java/chapt6/item38/README.md

[item 38](https://absorbed-cheek-029.notion.site/item38-e1f94d06a0cc4d93990c273d0de71b99)

item 38 - 확장할 수 있는 열거 타입이 필요하면 인터페이스를 사용하라.

---

app/src/main/java/com/programmers/java/chapt6/item39.md

[> 노션 바로가기 <](https://www.notion.so/DAY12-Annotation-68f703aa60174f4e80e05c5399997745)

item 39 - 명명 패턴보다 Annotation을 사용하라

---

app/src/main/java/com/programmers/java/chapt7/item43/README.md

[notion](https://www.notion.so/Item-43-380ddf5f9cac4005954f11ffd966f72b)

item43 - 람다보다는 메서드 참조를 사용하라

---

app/src/main/java/com/programmers/java/chapt7/item42/Item42_익명클래스_보다_람다를_사용하.md

[노션링크](https://morning-paprika-8fa.notion.site/Item42-badd9f20079c4286947ed7843eca011f)

item42 - 익명 클래스보다 람다를 사용하라

---

app/src/main/java/com/programmers/java/chapt7/item48/README.md

[notion으로 가기](https://bylog.notion.site/ITEM-48-bf444377089449268b013753112ca4c1)

Item48 - 스트림 병렬화는 주의해서 사용해라

---

app/src/main/java/com/programmers/java/chapt8/item49.md

[노션 바로가기](https://cat-tungsten-c56.notion.site/DAY14-ce4b6cbe3a8c434c859e5b24bb51e943)

Item49 - 매개변수가 유효한지 검사하라

---

app/src/main/java/com/programmers/java/chapt8/item50/item50_적시에_방어적_복사본을_만들라.md

Item50 - 적시에 방어적 복사본을 만들라

---

app/src/main/java/com/programmers/java/chapt3/item11/Main.java
app/src/main/java/com/programmers/java/chapt8/item51/MethodSignature.java
app/src/main/java/com/programmers/java/chapt8/item51/item51.md

열심히 개발하는 당신, 비즈니스 로직을 작성한다고 메서드 이름을 짓는데 소홀하지 않았는가요??
우리 모두 클린코드를 위해 열심히 노력합시다!
다들 프로젝트 화이팅입니다!
[메서드 시그니처를 신중히 설계하라](https://github.com/YHLEE9753/Effective-Java/blob/main/app/src/main/java/com/programmers/java/chapt8/item51/item51.md)

Item51 - 메서드 시그니처를 신중히 설계하라

---

app/src/main/java/com/programmers/java/chapt8/item52/Item52.java
app/src/main/java/com/programmers/java/chapt8/item52/ObjectOutputStreamTest.java
app/src/main/java/com/programmers/java/chapt8/item52/Wine.java
app/src/main/java/com/programmers/java/chapt8/item52/다중정의는_신중히_사용하라.md

[노션링크 바로가기](https://www.notion.so/Item52-6e891e60b11740cc944920225e329da2)
Item52  간략히 정리해보았습니다 :)

feat : item52 다중정의는 신중히 사용하라

---

app/src/main/java/com/programmers/java/chapt8/item56/Item56_항상_문서화_주석을_작성하라.md
app/src/main/java/com/programmers/java/chapt8/item56/JavaDocTest.java

[노션링크입니당](https://morning-paprika-8fa.notion.site/Item56-API-e703f9682112416db7486bc366e485c3)
* 예전에 자바독을 작성하는 습관을 들이려고 했었던 적이 있었는데 문서화 하는것은 중요하지만 주석에 너무 많은 설명이 의존적으로 들어가는 것은 오히려 유지보수에 좋지 않다고 생각이 들었습니다.
* 이번 아이템은 그냥 편하게 읽으셔도 될 것 같습니다 ~

Item56  - 공개된 API 요소에는 항상 문서화 주석을 작성하라

---

app/src/main/java/com/programmers/java/chapt9/item57/README.md

item57 - 지역변수의 범위를 최소화하라

---

app/src/main/java/com/programmers/java/chapt9/Item61/README.md

[노션링크입니당](https://morning-paprika-8fa.notion.site/Item61-53a128ba88cf493e84a896a46a7d3596)
* 이번 아이템도 편하게 읽어주시면 좋을 것 같습니다 ~!

Item61 - 박싱된 기본 타입보다는 기본 타입을 사용하라

---

app/src/main/java/com/programmers/java/chapt9/item62/README.md

item62. 다른타입이 적절하다면 문자열 사용을 피하라

---

app/src/main/java/com/programmers/java/chapt9/item63/README.md

[노션링크바로가기](https://morning-paprika-8fa.notion.site/Item63-71e48a50e595469fa06faa59d97d4313)
이번장은 내용이 많이 짧네요 편하게 읽으시면 될 것 같습니다 ~

Item63 - 문자열 연결은 느리니 주의하라

---

app/src/main/java/com/programmers/java/chapt9/item64/item64.md

[노션 바로가기](https://cat-tungsten-c56.notion.site/DAY17-c2e74e8631d249b8be380c986b50e8f2)

Item64 - 객체는 인터페이스를 사용해 참조하라

---

app/src/main/java/com/programmers/java/chapt9/item67/README.md

늦었습니당... 죄송합니다.. 예비 이슈가 있었습니다.. 말씀을 못드렸었네용...

item67 최적화는 신중히 하라

---

app/src/main/java/com/programmers/java/chapt10/item69/item69.md

[노션 바로가기](https://cat-tungsten-c56.notion.site/DAY18-c510100149e14c9ea7e0f4302ba426e4)

Item69 - 예외는 진짜 예외 상황에만 사용하라

---

app/src/main/java/com/programmers/java/chapt10/item72/README.md

item72 표준 예외를 사용하라

---

app/src/main/java/com/programmers/java/chapt10/item71/필요없는_검사예외는_피하라.md

[노션링크고고고!!!](https://morning-paprika-8fa.notion.site/Item71-0b78fe39d3714bc4a204639aeecbb4d0)
늦어서 죄송합니다 ㅠ
편하게 싫으시면 될 것 같습니다 :)

Item71 - 필요없는 검사 예외 사용은 피하라

---

app/src/main/java/com/programmers/java/chapt10/item74/item74.md

1장 짜리 아이템 입니다!
편하게 읽어 주세요~ 🙌
[노션 바로가기](https://cat-tungsten-c56.notion.site/DAY-19-a90461233833458ea812fe2666e16793)

Item74 - 메서드가 던지는 모든 예외를 문서화하라

---

app/src/main/java/com/programmers/java/chapt10/item76/가능한_실패가능한_원자적으로_만들라.md

Item76 - 가능한 한 실패 원자적으로 만들라

---

app/src/main/java/com/programmers/java/chapt11/item81/동시성_유틸리티를_애용하라.Md

- 깜빡하고 PR을 안했었네요 . . .ㅠㅠㅠ 죄송합니다

Item81 - wait와 notify보다는 동시성 유틸리티를 애용하라

---

app/src/main/java/com/programmers/java/chapt11/item83/item83_지연_초기화는_신중히_사용하라.md

저에게는 많이 어려웠던 내용 같습니다 
밤동안 내용을 추가하겠습니다 ㅠㅠ 지난번에 volatile 과 synchronized 를 나름 정리했다고 생각했는데 이해가 잘 안되네요..

Item 83 - 지연 초기화는 신중히 사용하라

---

app/src/main/java/com/programmers/java/chapt12/item88/item88_readObject_메소드는_방어적으로_작성하라.md

Item 88 - readObject 메소드는 방어적으로 작성하라

---

app/src/main/java/com/programmers/java/chapt12/item86/Item86.md

* 직렬화를 구현할 때 고려해야할 사항에 대해 많이 나와있지만 그 주의사항의 내용들은 온전히 이해하기엔 아직 어려움이 있네요 🧐 한번 편하게 읽어주시면 좋을 것 같습니다 :) 
(늦어서 죄송합니다 ..!)

Item86 - Serializable을 구현할지는 신중히 결정하라

---

app/src/main/java/com/programmers/java/chapt12/item87/item87.md

[노션 바로가기](https://cat-tungsten-c56.notion.site/DAY-22-3eedd057ca4f401f9963861365c7e126)

Item87 - 커스텀 직렬화 형태를 고려해보라
